### ISSUE TITLE
Multi-state or threeway switch

### ISSUE THREAD

**Issue by stofferr** [ArjanKranenburg/virtual-devices#100]
I want to create a virtual switch device with three states: off, on, auto. Setting the switch and reading the current switch value should be possible
I would appreciate if the switch can have configurable states , but predefined is fine for me.
I can use the switch device to control my lights either manual on or off, or with automatic control, using a scene that reads the switch value, or reacting to a switch state change.
I thought a multimode VD would allow me to do this, but I can't get this behavior to work.

**Comment by ArjanKranenburg** [comment]
Indeed this is what a MultiMode should do, but since V2 that isn't working anymore. Athom is giving me little room to manoeuvre here.

**Comment by ArjanKranenburg** [comment]
I'm giving up on this. And otherwise it will be a new app.
