### ISSUE TITLE
Sensor, power meter as Watts and KWh?

### ISSUE THREAD

**Issue by invensAB** [ArjanKranenburg/virtual-devices#106]
Hi
Im using the VD sensor and power, now it shows power as KWh.
Comparing to my fibaro wallplugs they show Power as W, watts. Power meter shows KWh as total consumption..
Could this be added to VD sensor, showing both power and power meter?
In my case I have a wemos sensor logging usage from the heating of our house, it sends through mqtt both watts and KWh..

Thanks

**Comment by poblom** [comment]
Just what I want to!! See #105

**Comment by Allram** [comment]
Created a pull request for this. Tested it myself and works great :)

https://github.com/ArjanKranenburg/virtual-devices/pull/108

**Comment by ArjanKranenburg** [comment]
Note:
When released use 'meter_power' for kWh
