### ISSUE TITLE
Virtual termostat not responding

### ISSUE THREAD

**Issue by 2tracer** [ArjanKranenburg/virtual-devices#113]
Hello.
The virtual termostat is not responding when:
My floor heat (water) is on, the temperature was stable at 22 degrees, so i wanted to turn down the heat, but the termostat do not get a temperature change so it will not close (shut off) valve.
The flow seems fine but the bug is that the termostat do not get a new reading (change) from the xiaomi temperature sensor because the water temp in floor is very stable. As a result no update to the virtual termostat, and so when i lower the temperature on the virtual device it will not aktivate the "close valve" flow because there are no trigger. (When temperature change on sensor, and temperature is more than target temp is true, then turn relay to off.)
Can there be made a fix on this bug?

**Comment by ArjanKranenburg** [comment]
Thanks for reporting!
Could you elaborate a bit more. From your description it looks as if there is no trigger, but you still want the virtual thermostat to react.
Perhaps with a screenshot of your flow. Thanks!

**Comment by ArjanKranenburg** [comment]
Without more info, there is nothing I can do.

**Comment by 2tracer** [comment]
I am sorry for very late response, there was no bug in the app, it was me that chose wrong tags 😇😇
