### ISSUE TITLE
Could a sensor have also on/off state?

### ISSUE THREAD

**Issue by oh2th** [ArjanKranenburg/virtual-devices#122]
I am setting up a virtual device to represent our sauna to:
- current temperature in sauna
- current humidity in sauna
- power W of the sauna stove
- on/off state for the sauna stove

Of these, the first three is possible, but the fourth can not be combined to the same VD. Any chance that on/off state could be added to the virtual sensor?

**Comment by klim123123** [comment]
It's would be great to have on/off state for sensors device. Please!

**Comment by oh2th** [comment]
Thank you
