### ISSUE TITLE
Switch icon dimmed in the App (HomeyDash)when on

### ISSUE THREAD

**Issue by markwi** [ArjanKranenburg/virtual-devices#130]
In this comment you said that in the App (and HomeyDash), the icon is dimmed in the off-state.

https://github.com/ArjanKranenburg/virtual-devices/issues/9#issuecomment-320991509

Mine seems to be reversed, dimmed when on and vice versa.

**Comment by ArjanKranenburg** [comment]
Thanks for reporting. Do you have some more information?
- Flow-cards
- Is it always reversed or once in a while?
- Is it still reversed after, say, 5 minutes or only when just changed?
- What capabilities did you use in the Virtual Device?
- Do all your Virtual Devices have this issue?
- Anything else that could be of importance...

**Comment by markwi** [comment]
These are the Flow-cards from 2 diffrent switches:

![2020-10-22 (9)](https://user-images.githubusercontent.com/73260540/96917374-218f4c80-14a9-11eb-9deb-42f5800c397b.png)
![2020-10-22 (10)](https://user-images.githubusercontent.com/73260540/96917403-28b65a80-14a9-11eb-9783-2f10465a34c5.png)
![2020-10-22 (11)](https://user-images.githubusercontent.com/73260540/96917425-2e13a500-14a9-11eb-9861-58ff33d2bcbf.png)
![2020-10-22 (12)](https://user-images.githubusercontent.com/73260540/96917438-323fc280-14a9-11eb-9ffc-5224425a5655.png)



- **_Is it always reversed or once in a while?_**  Yes, it is always reversed.
- _**Is it still reversed after, say, 5 minutes or only when just changed?**_ It seems like it changes when i use the switch. Than it stays in that position. Sometimes the switch doesn't work immediately, so i have to press it multiple times, it looks like the position changes at that point. 
_-**What capabilities did you use in the Virtual Device?**_ I've selected device to install, after that i've selected "light" as class. 
- _**Do all your Virtual Devices have this issue?**_ It seems like it. The flows from the two switches are made different at the "when" condition.
In one flow, i choose the "virtual Device" app as an event for the "when" condition. 

In the other flow, i've chosen for VD in "devices".

**Comment by markwi** [comment]
ArjanKranenburg Issue seems to be fixed. It seems there was a problem with the flows. As event by "When" i've stopped using the app (Virtual Devices). instead i choose the VD device. I also made some changes in choosing the condions ( some left blank). 
I think that the use of 2 different VD's (in combination with poor flows) caused the reverse of the VD (dimmed when on and bright when off). With my new flows, everything works perfect.

![2020-10-26 (2)](https://user-images.githubusercontent.com/73260540/97215148-6296a200-17c4-11eb-9714-282d2527f81c.png)
![2020-10-26 (2)](https://user-images.githubusercontent.com/73260540/97215322-95409a80-17c4-11eb-9aaf-4440065778b3.png)
![2020-10-26 (3)](https://user-images.githubusercontent.com/73260540/97215514-d5a01880-17c4-11eb-886a-c3ff1c5f9c6f.png)
![2020-10-26 (5)](https://user-images.githubusercontent.com/73260540/97215656-0718e400-17c5-11eb-8f45-02d3a9d53e6b.png)
![2020-10-26 (7)](https://user-images.githubusercontent.com/73260540/97215861-4e06d980-17c5-11eb-8f57-a319588d334d.png)
![2020-10-26 (8)](https://user-images.githubusercontent.com/73260540/97215975-72fb4c80-17c5-11eb-9b7c-def400a2dff1.png)
![2020-10-26 (10)](https://user-images.githubusercontent.com/73260540/97216076-9625fc00-17c5-11eb-92ab-09541e02388e.png)
