### ISSUE TITLE
Enable an interface to update Capability Values of virtual devices from HomeyScript

### ISSUE THREAD

**Issue by oh2th** [ArjanKranenburg/virtual-devices#132]
I would like to be able to set the capability values such as measure_temperature, measure_humidity and more from HomeyScript.
I am using MQTT client to receive measurements and process them with a HomeyScript to store those values now with Better Logic. However it would be even better if I could have VD sensors that would contain those as measure_* values.

**Comment by VitaliBabkin** [comment]
hello!
Should we expect enhancement so that the state of the sensor can be changed from HomeyScript?
Thanks.

**Comment by oh2th** [comment]
Since MQTT Hub has virtual device, that connects directly with MQTT topics, I do not need this anymore.
