### ISSUE TITLE
Test version crashes while removing VD's

### ISSUE THREAD

**Issue by PeterKawa** [ArjanKranenburg/virtual-devices#133]
Rapport id: 76057fe0-dfc0-4241-aa05-3b4cd722e793

v5.0.0

Het is geen ramp, maar toch gaat er ergens iets mis blijkbaar:
Al een aantal maal crashte de VD test app vandaag.
Ik was VD's aan het verwijderen, waar ik vooraf de gekoppelde flows losgekoppeld had.
Wellicht hebben jullie iets aan deze info.
![Screenshot_20210221-212959_Homey~01](https://user-images.githubusercontent.com/74005072/108638019-7cec3e00-748d-11eb-9ef5-6c0d23672619.jpg)

**Comment by ArjanKranenburg** [comment]
Thanks for reporting. I think this is solved in version 0.9.5. Can you retest?

**Comment by PeterKawa** [comment]
Sorry for the late response, Arjan.
I saw an app update the same evening, and then tried adding multiple devices, and deleted them afterwards. All's doing fine again!
Thanx for the quick fix!

**Comment by PeterKawa** [comment]
Issue closed
