### ISSUE TITLE
New HOMEY Pro 2023

### ISSUE THREAD

**Issue by CyberSponk** [ArjanKranenburg/virtual-devices#160]
Hi,

will be there a Version for new HOMEY Pro 2023 in future avaible? At the moment the App-Store shows that the App is not compatible with the new HOMEY Pro.

Kind Regards,
Nick

**Comment by djbakker** [comment]
That should be very nice. I like that also. 
Douwe-Jan

**Comment by MichalStranik** [comment]
I vote for this one too :)

**Comment by CyberSponk** [comment]
Take a look here:

 [https://community.homey.app/t/app-pro-virtual-devices/1723](https://community.homey.app/t/app-pro-virtual-devices/1723)

This app is no longer updated. It works how it works.
