### ISSUE TITLE
Virtueal Hue dimmer switch

### ISSUE THREAD

**Issue by Oy1974** [ArjanKranenburg/virtual-devices#17]
A Virtueal Hue dimmer switch... on-dim up- dim down - off . Inclusive once pressed on twice pressed on 3 pressed on. pressed dim up and hold dim up.

Not sure if its even possible, but would be great

**Comment by ArjanKranenburg** [comment]
I'll add the Hue light capabilities that Homey has as well:
		"light_hue",
		"light_saturation",
		"light_temperature",
		"light_mode" (although I'm not sure what this one does)
It'll be available later in 0.6.7.

If I deviate too much from the Homey capabilities, I'll end up in a code-nightmare just to find out that Homey does not support it. So I'll stick to these.
I also leave out the once pressed, twice pressed, etc. That would be a very special implementation with a timer and a counter. Perhaps later or in a different app.
