### ISSUE TITLE
request for curtains

### ISSUE THREAD

**Issue by Cyberhuis** [ArjanKranenburg/virtual-devices#19]
Can you add curtains? I now use the blinds option to open/close my curtains but it would be nice if the icon shows curtains and the uses open/close instead of up/down.

**Comment by ArjanKranenburg** [comment]
Note for myself:
Related to https://github.com/athombv/homey/issues/2056

And code in (local) branch windowcoverings_tilt

**Comment by ArjanKranenburg** [comment]
The new icon will be in version 0.6.7.
Sorry, but the terminology comes from the capabilities provided by Homey, and they chose for up / down. I cannot change that.

**Comment by Cyberhuis** [comment]
Thanks!
