### ISSUE TITLE
[Enhancement] Show visual confirmation when button pressed in Homey app.

### ISSUE THREAD

**Issue by SkorpionNL** [ArjanKranenburg/virtual-devices#21]
Hi Arjan,

First of all, I would like to thank you for the nice app and all the spare time you are investing in VD.

**My Problem**
In the Homey OS X app, I see a visual confirmation of a button device when the button is pressed.

In the Athom Homey iOS app there is no confirmation when a button is pressed. Often when I press, my flows are not fired. (This probably has to do with the slow iOS Athom Homey app itself). 

**My Question**
Is it possible to add a button pressed confirmation in the Homey iOS app just like in the OS X app, or is this a shortcoming of Athom's iOS app?

**Comment by ArjanKranenburg** [comment]
Thanks for the appreciation.

The button itself is indeed something from the iOS Homey App and there's nothing I can do about that from the VD-app. The icon is static and cannot be changed, also not for a short while, after creating the device.

But on the plus-side: Athom is developing a new version of the iOS (and Android) Homey App. I've seen the first (preliminary) version where the focus is more on functionality and less on looks, but even then the 'Press'-text gets lighter when pressed. So let's hope the final-version will keep that in some sort.
