### ISSUE TITLE
Virtual Thermostaat not accepting tags

### ISSUE THREAD

**Issue by iOurea** [ArjanKranenburg/virtual-devices#22]
![image](https://user-images.githubusercontent.com/23391397/31932218-05c4b7cc-b8a6-11e7-8767-4f6e41212e33.png)

When i test this flow the THEN part is not executed when a tag is used.
When a fixed value is used everything works well.

Version used is 0.6.6

**Comment by ArjanKranenburg** [comment]
This works for me, but a temperature must be between 4 and 35. Actually 4 isn't working either so it must be >4 and since Better Logic does not support decimals, the minimum in this test is 5.
Did you use a whole number between 5 and 35?

**Comment by iOurea** [comment]
No, I used decimal numbers like 15.4.
I have now used a whole number and it worked.
thx
