### ISSUE TITLE
Request for virtual Sensor

### ISSUE THREAD

**Issue by ramonzumstein** [ArjanKranenburg/virtual-devices#26]
It would be nice to have a device type Sensor (additionally to Device, State, State-Multi) where you can have multiple parameters, e.g. a virtual temperature sensor with temperature (number) and humidity(number). This would be helpful to save external values in a device (e.g. values from IFTTT)

**Comment by ingermaa** [comment]
+1 for temp/humidity sensor. I would also be useful with a power meter (current/usage)

**Comment by fredrikjohnsson** [comment]
+1 for all kinds of different sensors, like "Dummy" in Domoticz

**Comment by abeggled** [comment]
+1 and please add also text strings, thanks.

**Comment by ps-nl** [comment]
Check Pull Request #46, which has the following sensors: temp, humidity, pressures, CO2, PM25 . 
With reference to @ramonzumstein, I populate it with values pulled from a MQTT stream (using the MQTT client app).

**Comment by ArjanKranenburg** [comment]
Lot's of sensor-capabilities were already added.
If you need more, create a new issue with the specific capability.
