### ISSUE TITLE
virtual alarm states

### ISSUE THREAD

**Issue by LyoshaDovolen** [ArjanKranenburg/virtual-devices#29]
Hi Arjan. Please add virtual alarm states, like 
STAY_ARM 
AWAY_ARM 
NIGHT_ARM 
DISARMED
![alarm_](https://user-images.githubusercontent.com/31984722/33280102-2c8697fa-d3cb-11e7-8ba2-baa7c03db16b.jpg)

**Comment by ArjanKranenburg** [comment]
Hi Lyosha,

To keep the code maintainable, I don't want to deviate from the capabilities that are provided by Athom. 
Besides, they also overlap the current 3 states:
Home (Stay) -> 'Partially armed'
Away (Away) -> 'Armed'
Night (Night) -> 'Partially armed'
Off (Disarmed) -> 'Disarmed'

What does 'Night' mean? Is that when everybody is sleeping? Or is it a special case of 'Away'?
Perhaps you can use a mode in combination to indicate the 'Night'-state.
