### ISSUE TITLE
Remember state after reboot

### ISSUE THREAD

**Issue by StraDijk** [ArjanKranenburg/virtual-devices#30]
Homey Firmware: 1.5.5
App version: 0.6.6

When i reboot Homey, the state of the virtual devices(Alarm) is not remembered

**Comment by ivleth** [comment]
Same for me

**Comment by ArjanKranenburg** [comment]
Thanks for reporting, but I can't reproduce this.
Is Homey Firmware 1.5.5 an experimental version? I'm still on 1.5.3.
Is it only the Alarm or also the other devices?
What if you add a new Virtual Device? Does that have the same problem?

**Comment by StraDijk** [comment]
Looks like the state is saved again after 1.5.6 rc6 update
