### ISSUE TITLE
Homey - Samsung Multiroom

### ISSUE THREAD

**Issue by niels511** [ArjanKranenburg/virtual-devices#31]
Is it possible to connect the Samsung Multiroom system to a Athom Homey? So i can connect both systems to eachother.

**Comment by ArjanKranenburg** [comment]
Hi Niels,
Thanks for your suggestion. I don't know the Samsung Multiroom system, but I'm not sure if such support should be part of **Virtual** Devices. If we need a driver to connect to a real device, it would no longer be virtual and a device-specific app seems more in place.
Or do you see that different?

**Comment by niels511** [comment]
I'm sorry Arjan. I've made a mistake in posting an issue on your page. I'm new to Github and I try to get familiar with postings. I accidentally posted the issue.

I agree with you that i'm in need of a device specific app. My programming skills are not that great, so i've tried to create an issue on Github so someone maybe wants to help me.

**Comment by ArjanKranenburg** [comment]
You can post requests like this in the forum:
https://forum.athom.com/categories/ideas-suggestions
