### ISSUE TITLE
Humidity Values

### ISSUE THREAD

**Issue by ArjanKranenburg** [ArjanKranenburg/virtual-devices#32]
Hi Arjan,
Is it posible to add a device where we can add temperature an humidity values.
I want to use it for my itho mechanical ventilation. 
Thanks
Jeroen
Requested in the [app-store](https://apps.athom.com/#comment-59f719f6bb3fc31f0eee491f)

**Comment by ps-nl** [comment]
Arjan, Jeroen, 

I am looking for a similar virtual device as well. If the device also allowed for CO2 values, it would contain all the parameters that are relevant for automatic ventilation. 

Peter

**Comment by ps-nl** [comment]
Just created a Virtual Sensor to do this. See PR #46
