### ISSUE TITLE
Multimode  not triggerd sometimes

### ISSUE THREAD

**Issue by Oy1974** [ArjanKranenburg/virtual-devices#33]
setting a multimodus, not triggerd... in the device card it set on right modus, but to get the card triggerd need to push it again. This is not always the case. Sometimes it works sometimes not.

https://forum.athom.com/discussion/4442/zichtbaarheid-status-in-app#latest

**Comment by homdom** [comment]
i noticed the same problem. Sometimes it works sometimes not.

**Comment by Oy1974** [comment]
Not sure its related to this issue.

Setting multimode in a flow to example HOME works. But when having also a flow like....

![knipselmulti](https://user-images.githubusercontent.com/32013370/35639162-9364531a-06b9-11e8-9b0d-9f1f55fa562f.JPG)

Then it also trigger this flow, and its goes in a loop sometimes.

**Comment by ArjanKranenburg** [comment]
@Oy1974 & @homdom 
Small question: did you see this behaviour also with the beta-version, i.e. 0.7.1?

**Comment by Oy1974** [comment]
Gonna test it, this week(end). After i notice the bug i disabled it.

I let you know

**Comment by homdom** [comment]
i instal 0.7.1 and go test it

**Comment by Oy1974** [comment]
setting a multimodus, not triggerd... in the device card it set on right modus, but to get the card triggerd need to push it again. This is not always the case. Sometimes it works sometimes not.
https://forum.athom.com/discussion/4442/zichtbaarheid-status-in-app#latest

Tested a few days, and for now it looks oke

**Comment by homdom** [comment]
tested for a few days and i think it is soved
