### ISSUE TITLE
'Mode Changed' doesn't trigger from other flows

### ISSUE THREAD

**Issue by tregota** [ArjanKranenburg/virtual-devices#39]
'Mode Changed' doesn't trigger a flow when another flow has turned the mode on or off. Only when manually turning the mode on or off.

Also it seems to me like "Mode is on" shouldn't trigger when another flow tries to set a Mode that is already on to on. Or is that just me?

Thanks for a very useful app.

**Comment by DieterKoblenz** [comment]
Confirmed 👍

**Comment by Keverjeroen** [comment]
Is this in Dutch the 'een virtueel apparaat is veranderd'?

**Comment by DieterKoblenz** [comment]
Yes

**Comment by ArjanKranenburg** [comment]
Actually it is 'Modus Veranderd' in Dutch, but it is likely that the Virtual Device has the same issue as the Mode.
