### ISSUE TITLE
Custom virtual device

### ISSUE THREAD

**Issue by ricardoblonk** [ArjanKranenburg/virtual-devices#45]
hi arjan!

i am in the process of thinking how to automate or making my house aware of the things that happen inside the house. and the app virtual devices is a very big part of that proces! 

the app already provides a very big selection of devices and modes you can add to make your house automated, but i do miss the choice to select which sensors are in the virtual device because all the virtual devices are pre programmed which sensors it can have, and the rest of the options are disabled by default. you also cant combine the modes and devices with eatch other to make one custom virtual device!

 i would like to give you a example of a scenario where sutch a virtual device would be usefull. i own a ¨dumb¨ refrigerator that doesnt comunicate with homey but i still want homey to know what the tempreture of the fridge is and if the fridge is cooling and if the door is open. 
so i would like to make a virtual device and give it 1 tempreture sensor, 1 door sensor, 2 modes, and 1 power sensor. 

and in the flow editor i will make it that 

power conumpotion is higher than 100W --> set mode to cooling
power consumption lower than 20W --> set mode to idle 
when door is open for longer than 1 min --> send notification that door is open 
and i will always see on the tile in the homey app what the mode is, what the temprature is and if the door is open.

when you make virtual devices by assining virtual sensors and modes to the device you can make any device smart, and that would be awsome! i dont now how to program or to make this so maybe it isnt possible to do but i wanted to tell you anyway.

**Comment by ArjanKranenburg** [comment]
I'm not sure how to do this in a generic way.
You could create an app yourself with the specific capabilities for your situation.
