### ISSUE TITLE
Change Diplay Icon on Mode change?

### ISSUE THREAD

**Issue by chupacabra71** [ArjanKranenburg/virtual-devices#50]
is there a way to get the icon that gets displayed on the GUI to change to the icon of the mode selected?   I have a multi-mode VD that is set to the mode of the house (Home, Away, Vacation, night).  it would be nice to be able to see the icon for the mode be the main icon displayed on the GUI so that i know right off the bat what the mode is set to.  not sure if it is possible with Homey, but thought i would ask.

**Comment by ArjanKranenburg** [comment]
Unfortunately this is not possible... yet. The request for Athom is logged at:
https://github.com/athombv/homey/issues/1972

**Comment by chupacabra71** [comment]
I figured as much, and thanks for the prompt reply!

**Comment by ArjanKranenburg** [comment]
Closing this. Don't think athom will ever support this.
