### ISSUE TITLE
Feature request: TILT Hydrometer

### ISSUE THREAD

**Issue by Striffster** [ArjanKranenburg/virtual-devices#51]
I'm trying to figure out some nice way to show data from my beer fermentation and using a Tilt hydrometer https://tilthydrometer.com/. The device needs temperature and some kind of measurement to store SG (Specific gravity). At the moment I'm using TiltPi and have made an mqtt flow in Node-Red and saving the two values into two different VD Thermostats but I would like to have some device where I can have both values in the same device and the SG need three decimals.
![tilt](https://user-images.githubusercontent.com/7376682/38826834-45e39b40-41b1-11e8-8446-2d863ca030a8.jpeg)

**Comment by ArjanKranenburg** [comment]
I'm closing this. I don't see how to add this in VD (I don't want to create custom capabilities).
I'm guessing a specific app is your best chance.
