### ISSUE TITLE
Switched on trigger does not seem to work 

### ISSUE THREAD

**Issue by pim555** [ArjanKranenburg/virtual-devices#52]
Homey version: 1.5.9
Virtual Devices version: 0.7.3

Would like to use a virtual mode or switch to enable/disable a set of alarms. The set/unset alarms flows are triggered by this virtual mode switched on or off. Did work but now is not anymore. I tried both mode and switch.

**Comment by pim555** [comment]
Have deleted the flows as of a recent re-build of most flows. The strange thing that initially it did work but stopped working after some time.

Will try to reproduce in the next few days.

**Comment by ArjanKranenburg** [comment]
Hi Pim,

Did you reproduce this issue already. Is this still an issue?

**Comment by pim555** [comment]
Hi Arjan,

Re-built the flow and cannot reproduce anymore so let's close the issue.

Best
Pim
