### ISSUE TITLE
Virtual thermostat, please increase temp range

### ISSUE THREAD

**Issue by RobNoot** [ArjanKranenburg/virtual-devices#53]
Hi Arjan,
I use your great app for setting the temperature of my outdoor jacuzzi.....

I compare the virtual thermostat setting with a real fibaro waterproof thermometer to switch on/off the heater pump.

Unfortunately the water needs to be warmed to 37-40 degrees celcius.
And the max temp of the virtual thermostat only goes to 35 degrees :-(

Can you please increase the max temp range of the thermostat to 40 degrees for me?

Thank you in advance !
Rob

**Comment by ArjanKranenburg** [comment]
Thanks for your suggestion. Since I use the 'target-temperature' Capability, it's range is set from 4 to 35. I've requested to increase this to 40 or higher. See [Homey issue #2470](https://github.com/athombv/homey/issues/2470)

**Comment by ArjanKranenburg** [comment]
Answer from Jeroen (from Athom):

> @ArjanKranenburg You can indeed use the min/max to change it into your desired maximum. I'm not sure why it's not documented, leaving this issue open as request to update the docs.

**Comment by ArjanKranenburg** [comment]
Closing this. The range is now from 4 to 50, which should be enough for a jacuzzi.
