### ISSUE TITLE
Light temp tag

### ISSUE THREAD

**Issue by HansS63** [ArjanKranenburg/virtual-devices#54]
I have a lamp with 4 innr cold/warm white leds. I can use within Homey a tag to dim al the 4 ledlamps together. I have add the color temp. and see de color ring insite the virtual device. When I make a flow I can use the Tag to Dim all the lamps at the same time but doesn't see a tag to change from warm to cold vica versa.
Is there a way to make a flow to control this?

![image](https://user-images.githubusercontent.com/37303341/40139877-8a88aea4-5951-11e8-8669-db8057c7e7ed.png)

**Comment by ArjanKranenburg** [comment]
Did this work for you? Can we close this issue?

**Comment by ArjanKranenburg** [comment]
Assuming this is no longer an issue

**Comment by HansS63** [comment]
Hi Arjan, 
Sorry that I dindn't responded here. I thought I did...

The issue was solved with your help, thanks for that!!! I really appreciate your help
