### ISSUE TITLE
KWh meter for energy measurement

### ISSUE THREAD

**Issue by ArjanKranenburg** [ArjanKranenburg/virtual-devices#57]
Rijswijker wrote on the Forum
> Is it possible to add a KWh meter for energy measurement?
> The only thing i can do now is show the actual wattage, but not the total wattage in KWh.

**Comment by ArjanKranenburg** [comment]
I believe this is solved. If there is still an issue, feel free to open a new one.

**Comment by fmvdb** [comment]
Should meter_power (total power consumption / "energiemeter" ) update automatically when I've added a flow that adjusts the current power consumption ( measure_power / "energie")? 
Or should I add my own formula to update "total power consumption" as well?
