### ISSUE TITLE
virtual Window Door Sensor

### ISSUE THREAD

**Issue by LyoshaDovolen** [ArjanKranenburg/virtual-devices#58]
How about virtual Window Door Sensor?=)
alarm_contact

**Comment by MP-ICT-Diensten** [comment]
And then with Heimdall support, like this: https://forum.athom.com/discussion/comment/74831/#Comment_74831

**Comment by ArjanKranenburg** [comment]
I believe this is solved: alarm_contact was already added a while ago. If there is still an issue, feel free to open a new one.
