### ISSUE TITLE
Upload icons to app

### ISSUE THREAD

**Issue by rick00001** [ArjanKranenburg/virtual-devices#63]
Hello Arjan, great app. It is very usefull and very stable. 
I have a request, can you add a possibility that the user can upload its own icons. Then it would be possible to make a mutli device with for example radio or tv stations.

**Comment by ArjanKranenburg** [comment]
I got that request before, but unfortunately this is not possible with Homey.
The request for Athom to support that is logged here:
https://github.com/athombv/homey/issues/1972

**Comment by ArjanKranenburg** [comment]
Closing this. Don't think athom will ever support this.
