### ISSUE TITLE
Garage door

### ISSUE THREAD

**Issue by Maxwell70** [ArjanKranenburg/virtual-devices#64]
Hi! Please add garage doors.

**Comment by ArjanKranenburg** [comment]
Just the icons or do you need more?

**Comment by Maxwell70** [comment]
Additionally, i want to have such devices: purifier (with air quality) and humidifier.

**Comment by sirotkaslo** [comment]
Hi,
regarding garage doors, can you add a new class "garage door" with a push button (open/close) and a status (opened/closed)? 
I'm using opengarage.io and currently opening/closing them with button class, but this way I only get an mqtt notification about what it did with the latest action (door just opened or closed), but cant check current status (determined by distance - if that matters here). 
Thank you!

**Comment by ArjanKranenburg** [comment]
Thanks for the suggestions. Classes are defined bij Athom, I cannot add my own.
There is no 'Garage' class, but there is 'Windowcoverings' which is similar in its functionalities.

I can specify the capabilities to choose for a class and I see that there are 2 Window-coverings capabilities that are not yet supported bij VD: windowcoverings_closed and windowcoverings_set

I'll add those capabilities.

**Comment by sirotkaslo** [comment]
Yeah I took a look at those classes, will write to them to add this class, but for now a windowscoverings with  a button and those capabilities will do just fine! Thank you!

**Comment by dewenni** [comment]
I am also interested in a solution for my garage door.
The windowcoverings_state with up, idle, down can be used to control the garage door for open and close. But at the moment I can not find a nice solution to show the actual state of the garage door.

@ArjanKranenburg What about the plan to include the windowcoverings_closed and windowcoverings_set capabilities?
Would it be possible to have a status icon at the device to show if the garage door is open or closed?

I have tried also the "Home Alarm" class with the capability "Door/Window open" that have a alarm_contact. But also this does not show a status icon at the device button. You can only see the status if you "open" the device.

**Comment by tohmc** [comment]
I am also Interesses in Garagedoor with status of Open/closed.

**Comment by sirotkaslo** [comment]
I kinda solved this issue with an esp8266 with mqtt and I open/close doors with it and it also sends me a notification when either of these events happen. Then I bought a door sensor from xiaomi and I use it for open/closed statuses.

**Comment by tohmc** [comment]
Hi But how do you assoziate These two with each Other?
I Want an device that Control the Garagedoor and Give me the Status in one.
I dont know how to say.
Virtual device -> use Xiaomi to Show Status 
Virtual device -> use shelly to Control the Garage.
AND Show it as one device.

Sorry for my Pore english.
Did you unterstand what i want to explain?

**Comment by tohmc** [comment]
#sirotkaslo

Can you explain how you done this?

**Comment by sirotkaslo** [comment]
Sorry for my late reply, holiday season:) Unfortunately you can't have it as one device, I simply have one switch for opening and next to it xiaomi showing an alarm when the door is open. 
![IMG_4141](https://user-images.githubusercontent.com/32062426/61033201-3b477600-a3c3-11e9-983b-3aabcd018945.jpg)

**Comment by tohmc** [comment]
Ok thank you!

**Comment by ArjanKranenburg** [comment]
Closing this. If there is still an issue, feel free to open a new issue or request.
