### ISSUE TITLE
Extra sensor types

### ISSUE THREAD

**Issue by bassiebulk** [ArjanKranenburg/virtual-devices#66]
Please add:
- kWh (electricity over period)
- W (current E usage)
- m³ (gas)
- mm (rain)
- m/s (wind speed)
- 0-360º (or maybe N, NE, NNE etc. for wind directions)
- ? maybe some data for/from solar panel (azimuth, lux, altitude)

...as options for a virtual sensor devices.

**Comment by MagnusPer** [comment]
Please add Power (W) capability measure_power

**Comment by ArjanKranenburg** [comment]
I'm closing this. I've added most of them, if you still mis a capability that is also defined by Athom, feel free to create a new request for that.
