### ISSUE TITLE
Toggle flow.trigger and flow.action

### ISSUE THREAD

**Issue by kerkenit** [ArjanKranenburg/virtual-devices#7]
1. In the if column I want to use (if changed) so i can trigger a flow from my phone and it doesn't matter if it's on or off. Just trigger the flow.

2. In the then column (I want to set the device the other status)
For example: If I got visit. I say "Ik heb bezoek". The flow with speech contains "bezoek" should set the device "Virtual Event" to on.
With the same flow I want to trigger it of. So when I say "Het bezoek is weg" The flow with speech contains "bezoek" should set the device "Virtual Event" to off.
Every night a 5AM I set with the existing action the status to off.

Both request may work independently. But keep in mind. When constructing flows you can create a loop.

Thanks for your great work

**Comment by ArjanKranenburg** [comment]
1. is implemented, but not working. Testing the flow works, but the card is simply not triggered when the status is changed.

**Comment by ArjanKranenburg** [comment]
2. is also implemented, and should work.
