### ISSUE TITLE
No icons

### ISSUE THREAD

**Issue by Strike2001** [ArjanKranenburg/virtual-devices#77]
I'm running Homey beta 2 with your app beta app version 0.8.1 and there are no icons by adding new devices .

**Comment by Strike2001** [comment]
![Image](https://i.imgur.com/PBDiPDf.jpg)

**Comment by Strike2001** [comment]
- here is a link to the video on YT 
https://youtu.be/wSttH5gAL-g
you can see there the app v.8.1.0 on homey v2 installed in ios 12.1.3 beta running on iphone 7 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by daneedk** [comment]
@ArjanKranenburg 
This has to do with how the images are added to the device properties:

Compair a 'real' Device:
![image](https://user-images.githubusercontent.com/16610696/50561346-15516280-0d0a-11e9-92db-2a8f89d789e8.png)

and a virtual device from your app:
![image](https://user-images.githubusercontent.com/16610696/50561328-edfa9580-0d09-11e9-9e06-eb5429e2db42.png)

Somehow the image is written to the `icon` property instead of the `iconObj` property when added.
For Heimdall it is written to the `iconObj` property automatically, I have made no changes to the devices so I don't know why it's not working for your app while it is for mine.

![image](https://user-images.githubusercontent.com/16610696/50561403-990b4f00-0d0a-11e9-8860-a8d3992f37eb.png)

(Screenshots are the result of `Homey.devices.getDevices({ online: true });` in the [API Playground](https://developer.athom.com/tools/api-playground) )

**Comment by dewenni** [comment]
just to confirm that this is not an issue of one user. I have the same problem. No icons are displayed.

**Comment by ArjanKranenburg** [comment]
@daneedk Thanks!
Do you also have Virtual Devices that were added before going to Homey V2? Could it be that in the upgrade, the iconObj was created/added.
If so, with what is it set?
The icons seem to be copied to a different location and given an id. I've no clue what that id is (and the V2 documentation is excelling in absence).

**Comment by daneedk** [comment]
No, this is on my brand new development Homey, it's been updated to V2 before anything else. It seems indeed to be something in the process of adding a device where the icons are copied to a new path so I think it's something Athom should be fixing, you can report it here: https://github.com/athombv/homey-apps-sdk-issues/issues

**Comment by PeetersJan** [comment]
Hi, 
Same problem here.  Icons do not show.  I hope images help:  (V2.0/RC11; Virtual: 0.8.1):

![2019-01-06 20 03 45](https://user-images.githubusercontent.com/39444710/50740779-ccab1500-11f3-11e9-9474-749a4b671d8b.jpg)

![2019-01-06 20 03 56](https://user-images.githubusercontent.com/39444710/50740780-ccab1500-11f3-11e9-8d3f-783904194773.jpg)

**Comment by daneedk** [comment]
Just installed the Alpha, removed the virtual sensors and added them again:

Devices overview:

![image](https://user-images.githubusercontent.com/16610696/50755441-4c1eff80-1259-11e9-9974-e5b2655859db.png)

In Heimdall:

![image](https://user-images.githubusercontent.com/16610696/50755412-36113f00-1259-11e9-98e9-68190b70ec69.png)

And on the developer pages:

![image](https://user-images.githubusercontent.com/16610696/50755504-81c3e880-1259-11e9-946e-7ea894f804fb.png)

**Comment by ArjanKranenburg** [comment]
Thanks! I didn't change anything to the icons of the sub-modes in the multi-mode. Are they shown?

**Comment by PeetersJan** [comment]
Hi Arjan,
Just to let you know;
I have installed RC12 and created a new multi-mode.  Icons are not showing.
I have deleted the multi-mode and am now restarting my homey (to be sure).
I'll create a new multi-mode once again and will keep you posted.
Br,

**Comment by PeetersJan** [comment]
... no cigar; still no icons

![2019-01-07 21 42 36](https://user-images.githubusercontent.com/39444710/50792429-45c66d00-12c5-11e9-9923-8078d185cd1e.jpg)
![2019-01-07 21 42 44](https://user-images.githubusercontent.com/39444710/50792434-4828c700-12c5-11e9-8aac-e5d8dc37dde9.jpg)

**Comment by ArjanKranenburg** [comment]
@PeetersJan send me your e-mail-adres on slack (@arielaxed) or mail (Arjan.Kranenburg@gmail.com) and I'll give you access to the alpha.

**Comment by Strike2001** [comment]
hi , so Icons on , devices and mode are shown in the device overview 
by multimode the device icon works 
but the icons of the sub modes not shown 
![GitHawk Upload by Strike2001](https://i.imgur.com/o5Mcm3p.jpg)

and the name of the sub modes are not correct i added : Home and Away as example. 
but till now nice work . 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Strike2001** [comment]
its the 0.8.3 alpha on RC 13

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by daneedk** [comment]
@ArjanKranenburg 
I've made a Multi Mode device on V1 and V2 and selected the same options. 

Attached are the results from the developer pages. I hope it is of help.
[Multi-Mode V1.txt](https://github.com/ArjanKranenburg/virtual-devices/files/2742407/Multi-Mode.V1.txt)
[Multi-Mode V2.txt](https://github.com/ArjanKranenburg/virtual-devices/files/2742408/Multi-Mode.V2.txt)

Emile posted on slack today he's working on documentation and he was asked to include _Specific changes for V2 app UI; ie the replacement of the mobile card and all its options_ and he responded with a screenshot https://athomcommunity.slack.com/archives/C04SUGZ9E/p1547045134739500 showing just that so documentation is underway.

**Comment by ArjanKranenburg** [comment]
Just published a new alpha-version 0.8.4 with hopefully a fix for the sub-mode icons. But it's a long-shot.

**Comment by Strike2001** [comment]
no icons multimode 0.8.4 
( can you please add alarm_contact + alarm_motion to the sensors so that they can used with homekit.? ) 



<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ArjanKranenburg** [comment]
Logged issue on the SDK:
https://github.com/athombv/homey-apps-sdk-issues/issues/33

**Comment by ArjanKranenburg** [comment]
Athom's answer:
> You can set an icon for a custom capability using the button component.

That requires a rewrite of the app and I doubt if those icon's can be set during pairing. But then I could use default button's and perhaps set the name with:
```
"capabilitiesOptions": {
 "my_sensor": {
    "titleTrue": {
       "en": "True Value"
    },
    "titleFalse": {
       "en": "False Value"
    }
  }
}
``` 
(See also https://github.com/athombv/homey-apps-sdk-issues/issues/21 )

**Comment by ArjanKranenburg** [comment]
Multi-modes will be deprecated from the app in the next release. I'll remove the functionality after that.
