### ISSUE TITLE
No Sensors / homeykit app

### ISSUE THREAD

**Issue by Strike2001** [ArjanKranenburg/virtual-devices#78]
I talked in the last time often with the developer of the homeykit app to correct some errors . and now a problem showed when i add a new sensor ( temperature / alarm contact ) they could not added by this app to homekit like before. ( Homekit of athom is too experimental at this time and not very useful and also exposed the devices wrong example all sensors are shown as homekit switches 🙈) 
can you look at this error ? ( homeykit app plz)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ArjanKranenburg** [comment]
Please provide some more information:
Which Home(y)Kit app are you using, the one by Robert Klepp or Sprutt?
In case of HomeyKit, which version do you use? 2.1 or 3.0?
And which version of Homey are you running?
And what is the error-message? Something in the console?
What interface did you use to add new devices? Do devices that were already added still work?
Anything else I need to know?

**Comment by Strike2001** [comment]
i use the robert klepp homeykit v3.0 
homey running 2.0.0-rc.9 .
the console do not work , the device is also not available to add or delete from homekit list  by the settings page . 
yes devices which added before  are available in homekit and works , but they are also not visible in list of homeykit so i can t remove them if i want. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Strike2001** [comment]
https://github.com/swttt/com.swttt.homekit/issues/107#issuecomment-452234139

please correct this little problem . 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Strike2001** [comment]
i added these 2 lines ~~~~![GitHawk Upload by Strike2001](https://i.imgur.com/akbl6hV.jpg)
now i can choose the as sensor and also visible in homekit . 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ArjanKranenburg** [comment]
These were already added in a previous release
