### ISSUE TITLE
V2 Multi-mode can be toggled

### ISSUE THREAD

**Issue by ArjanKranenburg** [ArjanKranenburg/virtual-devices#82]
Toggling does not make sense, because which multi-mode to set.
Should I use another class? Or set a capabilitiesOption?

**Comment by ArjanKranenburg** [comment]
See:
https://github.com/athombv/homey-apps-sdk-issues/issues/36

**Comment by giggo** [comment]
How about selecting the modes using a text selector (see Vacuum in groups app)

**Comment by ArjanKranenburg** [comment]
I can look into that. The problem is that for a generic solution, I cannot define the list upfront.
