### ISSUE TITLE
Missing On/Off image

### ISSUE THREAD

**Issue by robiebab** [ArjanKranenburg/virtual-devices#9]
currently if the state is on or off it get's the same image. it would be nice to make a diffrence between them

**Comment by ArjanKranenburg** [comment]
In Homey, it is only possible to set an image when pairing (i.e. in the beginning, when setting up the device). Unfortunately, the image cannot be changed after that.
In the App (and HomeyDash), the icon is dimmed in the off-state. That's all we can do, unfortunately.
