### ISSUE TITLE
V2 and VD085: tags in changed card not accessable

### ISSUE THREAD

**Issue by thomahawk72** [ArjanKranenburg/virtual-devices#90]
None of the three tags in the pressed/changed card is visible in action cards. Only visible in the AND-clause cards

**Comment by ArjanKranenburg** [comment]
Thanks for reporting. Can you elaborate a bit more?
Which 3 tags? How do you expect them to become visible?

**Comment by thomahawk72** [comment]
Sorry for being unclear.
When adding a "A virtual device changed" chard to a flow, three tags are provided to be used in the the rest of the flow:
![20190125_124038](https://user-images.githubusercontent.com/37381653/51744020-cdbabe00-209e-11e9-8cb0-c1943d4bde3f.jpg)

None of these tags are to be found and used in any THEN-cards. So, it's not possible to use the tags for anything..
(except if you add an AND-clause to the flow that can accept a tag as input (ie. Logic card), then, for the AND-card the tags from the WHEN-card is visible and usable)

**Comment by ArjanKranenburg** [comment]
Ah OK.
Note that the trigger card is for a Virtual Device in general and is defined on App-level.
As soon as you e.g. turn a VD called 'Virtual Light' on (directly with the device or in another flow), the
'A Virtual Device Changed'-card is triggered. And with that the tags are set to, in this example, device=Virtual Light, variable=onoff, value=true.
These tags can then be used in the 'And'-flow to not act e.g. when another Virtual Device is changed.
(Perhaps in this example you could use the trigger-card of the Virtual Light in stead)

If you want to change the state of a(nother) Virtual Device in the Then-part, you just need to set it using the normal cards that come with the capability.

**Comment by thomahawk72** [comment]
Thanks :)
