### ISSUE TITLE
Request: Weather Station

### ISSUE THREAD

**Issue by k4mrat** [ArjanKranenburg/virtual-devices#97]
Maybe this is possible and I’ve just missed it, but:
Would it be possible to make a Virtual Weather Station with multiple inputs for Temp, humidity, wind etc? I gather data from a lot of different points, but can’t figure out how to add them all to one page/device.

**Comment by ArjanKranenburg** [comment]
Did you try to use class 'sensor'. Then you can add various of the mentioned capabilities.
See also:
https://arjankranenburg.github.io/virtual-devices/sensor

**Comment by k4mrat** [comment]
Sorry for answering late, totally missed that you had answered until you closed the issue.

I'm talking about adding multiple of the same input, like for example Fibaros Universal Sensor. i've achieved this somewhat by adding sub-capabilities when messing around in your code.

like "measure_temperature.sensor1", "measure_temperature.sensor2" etc.

I have a separate version of the VD running this as an experiment. Never got it to look pretty, but it worked for me so I haven't pursued the issue any more. I think i did add you to the private repository way back if you feel like taking a look, but as far as i'm concerned i'm happy with having the ugly hack side by side with the real app.
![image1](https://user-images.githubusercontent.com/48549512/72475239-d42fd180-37ea-11ea-911e-6f109f419a0d.jpeg)

**Comment by ArjanKranenburg** [comment]
I'm glad you did make your own changes. I encourage that. Often it is easier to make a tailored adaptation than a generic solution. Also in this case I can imagine adding Custom Capabilities is easier.

I tried to look at your changes, but could not find them. Did you push your changes to GitHub? Otherwise which files were changed?
